### ISSUE TITLE
mac parse m3u

### ISSUE THREAD

**Issue by testermania** [Romaxa55/IPTV_ReStreamer_GoLang#1]
hi;

**Comment by Romaxa55** [comment]
> hi;
> 
> Can you add parse this m3u link style for iptv-proxy fork? 0.5.6 is incorrectly parse.
> 
> url:80/play/live.php?mac=01:01:01:01:01:01&stream=1124&extension=ts

Hello, sure, comment please curl request and response, i need check it.

**Comment by testermania** [comment]
maybe this fork https://github.com/pierre-emmanuelJ/iptv-proxy/compare/master...mattetti:stream-proxy:master helping you for some stb urls and another custom User Agent change option adding.
